/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 1;
  /** RegularExpression Id. */
  int STRING = 2;
  /** RegularExpression Id. */
  int CHARAC = 3;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int ENDS = 5;
  /** RegularExpression Id. */
  int END1 = 6;
  /** RegularExpression Id. */
  int END2 = 7;
  /** RegularExpression Id. */
  int ARROW = 8;
  /** RegularExpression Id. */
  int EOL = 9;
  /** RegularExpression Id. */
  int OPEN = 10;
  /** RegularExpression Id. */
  int NOTE_START = 11;
  /** RegularExpression Id. */
  int REL = 12;
  /** RegularExpression Id. */
  int CLOSE_NOTE = 13;
  /** RegularExpression Id. */
  int ID_CLASS = 14;
  /** RegularExpression Id. */
  int BARRA_CLASS = 15;
  /** RegularExpression Id. */
  int CLOSE_CLASS = 16;
  /** RegularExpression Id. */
  int BARRA_MEMBERS = 17;
  /** RegularExpression Id. */
  int EOL_MEMBERS = 18;
  /** RegularExpression Id. */
  int CLOSE_MEMBERS = 19;
  /** RegularExpression Id. */
  int OPEN_METHODS = 20;
  /** RegularExpression Id. */
  int EOL_METHODS = 21;
  /** RegularExpression Id. */
  int CLOSE_METHODS = 22;
  /** RegularExpression Id. */
  int OPEN_PAR = 23;

  /** Lexical state. */
  int PAR = 0;
  /** Lexical state. */
  int METHODS = 1;
  /** Lexical state. */
  int MEMBERS = 2;
  /** Lexical state. */
  int CLASS = 3;
  /** Lexical state. */
  int NOTE = 4;
  /** Lexical state. */
  int DEFAULT = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ID>",
    "<STRING>",
    "<CHARAC>",
    "<NUM>",
    "<ENDS>",
    "<END1>",
    "<END2>",
    "<ARROW>",
    "<EOL>",
    "\"[\"",
    "\"[note:\"",
    "<REL>",
    "\"]\"",
    "<ID_CLASS>",
    "\"|\"",
    "\"]\"",
    "\"|\"",
    "<EOL_MEMBERS>",
    "\"]\"",
    "\"(\"",
    "<EOL_METHODS>",
    "\"]\"",
    "\")\"",
    "<token of kind 24>",
    "<token of kind 25>",
    "<token of kind 26>",
    "<token of kind 27>",
  };

}
