/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 1;
  /** RegularExpression Id. */
  int STRING = 2;
  /** RegularExpression Id. */
  int CHAR = 3;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int ENDS = 5;
  /** RegularExpression Id. */
  int END1 = 6;
  /** RegularExpression Id. */
  int END2 = 7;
  /** RegularExpression Id. */
  int ARROW = 8;
  /** RegularExpression Id. */
  int EOL = 9;
  /** RegularExpression Id. */
  int COMENTARIO = 10;
  /** RegularExpression Id. */
  int REL = 11;
  /** RegularExpression Id. */
  int OPEN = 12;
  /** RegularExpression Id. */
  int NOTE_START = 13;
  /** RegularExpression Id. */
  int EOL_COMENT = 14;
  /** RegularExpression Id. */
  int ID_COMENT = 15;
  /** RegularExpression Id. */
  int CLOSE_NOTE = 16;
  /** RegularExpression Id. */
  int CHAR_NOTE = 17;
  /** RegularExpression Id. */
  int ID_CLASS = 18;
  /** RegularExpression Id. */
  int BARRA_CLASS = 19;
  /** RegularExpression Id. */
  int CLOSE_CLASS = 20;
  /** RegularExpression Id. */
  int BARRA_MEMBERS = 21;
  /** RegularExpression Id. */
  int EOL_MEMBERS = 22;
  /** RegularExpression Id. */
  int CLOSE_MEMBERS = 23;
  /** RegularExpression Id. */
  int OPEN_METHODS = 24;
  /** RegularExpression Id. */
  int EOL_METHODS = 25;
  /** RegularExpression Id. */
  int CLOSE_METHODS = 26;
  /** RegularExpression Id. */
  int OPEN_PAR = 27;

  /** Lexical state. */
  int PAR = 0;
  /** Lexical state. */
  int METHODS = 1;
  /** Lexical state. */
  int MEMBERS = 2;
  /** Lexical state. */
  int CLASS = 3;
  /** Lexical state. */
  int NOTE = 4;
  /** Lexical state. */
  int COMMENT = 5;
  /** Lexical state. */
  int DEFAULT = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ID>",
    "<STRING>",
    "<CHAR>",
    "<NUM>",
    "<ENDS>",
    "<END1>",
    "<END2>",
    "<ARROW>",
    "<EOL>",
    "\"//\"",
    "<REL>",
    "\"[\"",
    "\"[note:\"",
    "\"\\n\"",
    "<ID_COMENT>",
    "\"]\"",
    "<CHAR_NOTE>",
    "<ID_CLASS>",
    "\"|\"",
    "\"]\"",
    "\"|\"",
    "<EOL_MEMBERS>",
    "\"]\"",
    "\"(\"",
    "<EOL_METHODS>",
    "\"]\"",
    "\")\"",
    "<token of kind 28>",
    "<token of kind 29>",
  };

}
