/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int ENDIF = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int StartCOM = 11;
  /** RegularExpression Id. */
  int EndCom = 12;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int NUM = 15;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COM = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 13>",
    "<ID>",
    "<NUM>",
  };

}
